linuxmint/muffin

src/core/window.c
This fixes switching out of fullscreen Direct3D applications running in
Wine. See issue 169 for more details.
=> Allow programmatic minimization without MWM_FUNC_MINIMIZE

Makefile.am, configure.ac, debian/control, debian/muffin-doc.install, debian/rules, doc/Makefile.am, doc/reference/Makefile.am, doc/reference/muffin-docs.sgml.in, doc/reference/muffin-overview.xml, doc/reference/running-muffin.xml, src/core/keybindings.c
Inside the doc, muffin takes the module name "muffin" instead of "meta"
to avoid conflicts with mutter.
Since gtk-doc uses the mighty xml, all occurences of "<" and ">" in
comment blocks will make gtk-doc very sad, and must be converted to `&gt;`
and `&lt;`
=> Add muffin gtk-doc building

src/compositor/meta-plugin-manager.c, src/compositor/plugins/default.c, src/meta/meta-plugin.h
The kill-switch-workspace signal is used when before switch-workspace
signal is fired for the existing switch animation to be cancelled.
However, this mechanism is not ideal since the switch-workspace and
kill-switch-workspace events are separated.
Using the old model, say we switch to left workspace, and during that
animation, we press Ctrl-Alt-Right to switch back to the right
workspace. What would happen is that we will finish the animation early,
land on the left workspace, and start a new animation.
By letting the wm handle the killing work when receiving the
switch-workspace, we can do better. We can immediately halt the windows'
movement, and let them animate to where Ctrl-Alt-Right would bring them
to, from the position where they started, which would look smoother.
This new way …
=> Remove kill-switch-workspace signal

src/compositor/meta-window-actor.c, src/core/display.c, src/core/window.c
Based on https://git.gnome.org/browse/mutter/patch/src/core/window.c?id=6190ae3873588aa1813ee4824bfff73bc1c75e5c
https://bugzilla.gnome.org/show_bug.cgi?id=752047
The change seems backwards compatible with older g-i versions
=> Remove invalid (transfer) annnotations

src/compositor/compositor.c, src/compositor/meta-window-actor.c
You can see the issue if you open two windows and put one partly covering the other. Close the window in the back and it will flash on top. This fix prevents that from happening.
=> window-actor: Keep in compositor's window list until destroyed

src/ui/theme.c
gtk 3.20 complains if the state passed doesn't match the context's current
state. This quiets a lot of log spam when window focus changes.
thanks to JosephM for finding this commit which turned out to be the exact
fix needed:
https://github.com/GNOME/mutter/commit/9b9083180f211cc4f19750de84c92dd8541c8848
=> theme.c: get style context state instead of using GTK_STATE_FLAG_NORMAL

src/core/window.c
this causes popup placement issues with gtk 3.20 as described in the
mutter commit this is based on. the assertion is left out, as we still
need to send configure notifies for OR windows in other cases.
based on:
https://github.com/GNOME/mutter/commit/e3622275147181a2876e45397f5fc7ed063b8bb8
Fixes #224
Fixes linuxmint/Cinnamon#5202
Fixes linuxmint/Cinnamon#5195
=> window.c: don't send configure notifies for OR windows

po/Makefile.in.in, src/compositor/compositor.c, src/compositor/meta-window-actor.c, src/core/window.c
remove the old tooltip placement code from https://github.com/linuxmint/muffin/commit/9bda8d2899a41809621ef9bef6db0c94d7ca0f02. This actually cause an issue where large tooltips that don't fit on-screen above or below the cursor flicker and then die. This allows them to draw and extend offscreen above the panel.
Requires: https://github.com/linuxmint/Cinnamon/pull/5222
=> compositor: Rework handling of our top_window_group

configure.ac
python has never been used in muffin, this is a remnant from a
workaround that was introduced to mutter in 2010, and removed
before muffin was forked.
original commit which introduced it:
https://github.com/GNOME/mutter/commit/7853bb804273eb18faaf5b54cd82c11c066978bc
=> autoconf: remove unneeded check for python

src/compositor/meta-window-actor.c
https://github.com/GNOME/mutter/commit/4d437e32e069d348e9ff55bdaf34cfec60b0c7e3
=> window-actor: fix leaked frame list

src/compositor/cogl-utils.c
It's quite easy to create situations where limiting the texture to the screen size causes issues. Instead textures up to the screen size * 2.
Fixes https://github.com/linuxmint/Cinnamon/issues/5363
=> cogl-utils: Don't set such a tight restriction on texture sizes

src/compositor/meta-window-actor.c
837aeb1 fixes windows not being unredirected by the heuristic when located on a monitor that is not located at 0,0 in the screen.
The other 3 commits fix some misbehavior and a crash introduced with https://github.com/linuxmint/muffin/commit/e5460a3a8ccd81d9182755accf028075027b65c9
More info on the crash here:
https://bugzilla.gnome.org/show_bug.cgi?id=740133
https://bugzilla.redhat.com/show_bug.cgi?id=1149409
Edit: The application I reproduced the crash with locally was Universe Sandbox ²
Fixes #249
=> Unredirect fixes

src/Makefile.am, src/compositor/meta-background-actor-private.h, src/compositor/meta-background-actor.c, src/compositor/meta-background.c, src/compositor/meta-background.h
Add a new meta-background object to actually hold the bg images. Use two of these as children of the meta-background-actor to create a fade effect.
This could be expanded on in the future by allowing "groups" of 2, one for each monitor, to allow per-monitor backgrounds.
=> backgrounds: Add a simple crossfade effect on bg transitions

src/core/muffin.c, src/tools/muffin-grayscale.c
removes some distracting deprecation warnings
=> remove deprecated unnecessary g_type_init calls

src/compositor/meta-background.c, src/compositor/meta-background.h
Fix the use of a wrong type and add a generic gpl header to meta-background.c
=> backgrounds: Clean up a couple things

src/core/constraints.c
Fixing linuxmint/Cinnamon#5343
=> Don't remove client-side frame extents when maximizing

src/core/screen.c, src/core/window.c
* This is just a port of the [fix which was applied to mutter](https://git.gnome.org/browse/mutter/commit/?id=8ab136b) to solve [their bug](https://bugzilla.gnome.org/show_bug.cgi?id=702564)
* This (hopefully) closes #267 (which helped by referencing the above bug)
NB: I have been using Cinnamon for a couple of days (on Debian Unstable/experimental), and did this PR because - even worse than the case reported in #267 - for me the .xsession-errors was getting spammed at *hundreds* of lines per second, with *or* without a second monitor attached (or perhaps the logging was just still clearing its buffers when I checked after disconnecting the second monitor). After a few days the log had surpassed a hundred megabytes worth of `Window manager warning: Log level 8: …
=> Fix meta_screen_get_monitor_geometry override redirect

src/compositor/meta-background-actor.c
When dispose() is called more than once we call meta_background_set_visible_region()
with an invalid top_actor. Make sure the top and bottom actor are NULL after the
first dispose() is called so we can avoid this.
=> meta-background-actor: Fix a warning when dispose is run multiple times

src/core/keybindings.c
Function "handle_raise_or_lower (src/core/keybindings.c)" is called
when running 'raise-or-lower' on a window. This function iterates
through all the windows in the stack to determine if our window is
already on top or obscured. The problem is that the window stack
includes windows in another workspaces and also windows that are
minimized.
https://github.com/linuxmint/muffin/issues/277
gnome/mutter was also affected by this problem. I submitted this patch to them too and it has already been accepted.
bug report: https://bugzilla.gnome.org/show_bug.cgi?id=705200
commit: https://git.gnome.org/browse/mutter/commit/?id=58669e7
=> keybindings: fix erratic raise_or_lower behavior

src/core/xprops.c
https://github.com/GNOME/mutter/commit/5ba38a4ab6913fc5a4005ec3195df6bff5e89821#diff-b2af4604a281ca9065ebb6453a6dca38
adapted
=> x11/xprops: Plug a memory leak

src/core/workspace.c
Right now, up/down animations proceed at angled directions. This seems
to be because |get_wrapped_horizontal_direction| assumes that |from|
and |to| are always different values.
In theory, this should resolve issue #302. However, I'm having a hard time figuring out how to verify this in a full cinnamon runtime. Can I run my locally-built muffin replacement with my stable cinnamon build? Do I need to do a full cinnamon build + all of its dependencies to be able to verify this muffin change? Some pointers would be appreciated. Thanks!
=> Fixes workspace animation direction for grid systems.

src/compositor/meta-background.c, src/compositor/meta-window-group.c
helps to avoid full stage redraws
see: https://bugzilla.gnome.org/show_bug.cgi?id=694988
=> Report paint volumes

src/core/prefs.c, src/meta/common.h
Fix `meta_prefs_get_button_layout`, in continuation with 68307b8c120216a1c227cb571f9c7fc0e5a164a3.
See https://bugzilla.gnome.org/show_bug.cgi?id=689263
=> Make MetaButtonLayout usable from introspection

src/core/screen.c
Redefine a fullscreen monitor as one where there is a
fullscreen window *and* that window is the topmost on that monitor.
Currently, when a window is fullscreen, and the user switches to
another window, the panels remain hidden, still affected by the
no-longer-focused fullscreen window.
=> screen.c: Refine definition of a fullscreen monitor

src/core/window.c
Otherwise we don't get the 'in-fullscreen-changed' signal from MetaScreen
in certain fullscreen cases when moving windows.
=> window.c: queue a fullscreen check when a window leaves a monitor

src/compositor/compositor.c
Based on
https://github.com/GNOME/mutter/commit/e15bc372255ac0954b22218a38427dde34c23118
=> compositor: map overlay window before redirecting windows

src/compositor/compositor.c
Based on
https://github.com/GNOME/mutter/commit/889844b004a5fd8ce032ea2f7c38f6ed4e5c4363
Possibly related to #333
=> compositor: sync stacking of window actors even if they're not parented to the window groups

src/compositor/compositor.c
Based on
https://github.com/GNOME/mutter/commit/660eceb61a9ce38322e3f2146f5b41dc6facfa59
=> compositor: Fix ClutterTimeline usage

src/compositor/cogl-utils.c, src/compositor/cogl-utils.h, src/compositor/meta-background-actor.c, src/compositor/meta-background.c, src/compositor/meta-background.h, src/compositor/meta-shadow-factory-private.h, src/compositor/meta-shadow-factory.c, src/compositor/meta-shaped-texture.c, src/compositor/meta-texture-tower.c, src/compositor/meta-texture-tower.h, src/compositor/meta-window-actor.c, src/meta/meta-shaped-texture.h
Partially based on:
https://github.com/gnome/mutter/commit/7f6a77232faa0560080e03834b8cec7aeb505be7
This is a straight-forward API update with no upstream refactoring. Adapting the changes directly breaks shadows.
=> Remove remaining deprecated Cogl 1.0 usage

src/core/window.c
These are freed on reload in window-props.c, but not on finalize.
=> window: Fix a couple leaks

src/core/window-props.c
Fixes warnings such as:
```
Cinnamon warning: Window 0xca00001 (No Man's S) sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
```
Based on:
https://github.com/gnome/mutter/commit/ae73e9d84d72ab55a1cae0626763039d645ce7c7
=> Double check whether the user time window was previously used

clutter/clutter/clutter-master-clock-default.c, clutter/clutter/cogl/clutter-stage-cogl.c, clutter/clutter/cogl/clutter-stage-cogl.h
I applied a similar patch from the Ubuntu Mutter patch series in #335, but overlooked this newer, updated branch on Daniel van Vugt's fork of Mutter. These commits improve smoothness noticeably over the original patch, and fixes the dismantling of the ability to fully disable vblank. 
The FIXME commit's X11 performance comment had me curious, so I assigned `refresh_interval` a 0 value in `clutter_stage_cogl_schedule_update`. It seems to improve input latency without affecting frame sync.
=> clutter: Improve smoothness of visuals

src/core/screen.c, src/core/window.c
- In screen, `meta_compositor_hide_tile_preview` and `meta_compositor_hide_hud_preview` are now guarded by a check on `tile_preview_visible` and `tile_hud_visible` respectively.
- In window, in `update_move`, calls to those functions now only occur when `tile_mode` is not `META_TILE_NONE`.
Not seeing any regressions with tiling, snapping, and the rendering of their related OSDs in Cinnamon. I used the following proxy in windowManager.js to see what functions are getting called and when.
```js
let keys = Object.getOwnPropertyNames(WindowManager.prototype);
for (let i = 0; i < keys.length; i++) {
if (typeof WindowManager.prototype[keys[i]] === 'function') {
let orig = WindowManager.prototype[keys[i]];
WindowManager.prototype[keys[i]] = new Proxy(orig, {
apply(target, thisA, args) {
log(new …
```
=> Only emit tiling-related signals when needed

clutter/clutter/clutter-actor.c
This is intended to help prevent full-stage relayouts during animations.
Partially based on: https://gitlab.gnome.org/GNOME/mutter/merge_requests/238
=> Avoid clutter_actor_queue_relayout in animations

clutter/clutter/clutter-actor-box-private.h, clutter/clutter/clutter-actor-box.c, clutter/clutter/clutter-offscreen-effect.c, clutter/clutter/clutter-paint-volume.c, clutter/tests/conform/Makefile.am
Based on:
https://gitlab.gnome.org/GNOME/mutter/merge_requests/117
This corrects an issue when using Clutter.set_offscreen_redirect on clones, which caches actors on the GPU and is applied to all children, so this would be needed if we were to take advantage of those kinds of optimizations in Cinnamon. Also subjectively, this branch seems to improves performance.
=> clutter: Fix offscreen-effect painting of clones

src/core/screen.c, src/core/window.c
These checks from #354 were causing the HUD display to not disappear in some cases when tiling windows.
This also fixes some formatting issues in update_move.
=> Fix up tile signal optimization

configure.ac
The current check includes the subdir unless it's explicitly disabled, but only builds the Makefile if it's explicitly disabled. This means the entire project fails to build while processing the docs folder, even if docs are disabled and a no-op... unless clutter docs are separately disabled.
=> always process clutter Makefile.in

src/compositor/meta-window-actor.c
Some framed windows, such as Firefox and VSCode, need their mask texture updated when maximized.
=> window-actor: Queue mask texture update on maximize

src/core/main.c
This was an old work-around for 3.8 that no longer works correctly, and breaks compositing.
Closes https://github.com/linuxmint/Cinnamon/issues/7985
=> main: Reserve CLUTTER_PAINT for software rendering only

src/compositor/meta-shaped-texture.c
This isn't necessary here and causes two additional redraws any time `check_needs_reshape` is called, which is the only caller for `meta_shaped_texture_set_shape_region`. `clutter_actor_queue_redraw` is always called at the end of `check_needs_reshape` via `meta_window_actor_invalidate_shadow`. There is an is_frozen() check guarding the redraw, but `check_needs_reshape` will only be called while unfrozen.
We are currently redrawing windows when the shape region is `NULL`, a state of the window we wouldn't want to show, and right after the shape region is set, before the mask texture and corners are computed.
=> shaped-texture: Don't redraw when setting the shape region

src/core/constraints.c
VLC fullscreen controller's window type was changed in commit
https://git.videolan.org/?p=vlc.git;a=commit;h=d60312d3ad4c4e27f3455b4f579999b826d3948c
Since then, it got pushed up by the height of a bottom panel, so that it was not displayed at the bottom monitor edge.
This fixes it.
This will also affect other "normal" windows that have a transient
parent in fullscreen and might need testing for those (wherever they might be)
=> Fix VLC fullscreen controller position

src/core/display.c, src/core/window-private.h, src/core/window.c, src/meta/atomnames.h
https://bugzilla.gnome.org/show_bug.cgi?id=786363
https://bugzilla.gnome.org/show_bug.cgi?id=786365
Adapted from
https://github.com/gnome/mutter/commit/e3d59832c56dbc6acb4301836bc54c467889d515
https://github.com/gnome/mutter/commit/92340fd8da1edd5b9c182f6284a791f6a17ce27c
Ref #326
=> window: Implement _NET_RESTACK_WINDOW and XConfigureRequestEvent sibling

clutter/clutter/clutter-stage.c
This reverts commit 2e88f14d3ac385f3448fd96c5db102cf3e7f28ce.
This patch causes a [regression](https://gitlab.gnome.org/GNOME/mutter/merge_requests/168) with dragging operations when mice run at a 1000hz polling rate.
=> Revert "clutter: Deliver events sooner when possible"

.gitignore, debian/muffin.install, debian/rules, src/Makefile.am, src/compositor/compositor.c, src/core/display-private.h, src/core/display.c, src/core/restart-helper.c, src/core/restart.c, src/meta/main.h
This works by first notifying Cinnamon with the `restart` signal so components and xlets can wind down read/write operations on the file system. Muffin will then freeze the image and restart itself.
Adapted from GNOME/mutter@3a57f84
=>  Make transitions between restarts seamless

src/compositor/meta-window-actor.c
This fixes the case when clients try to re-map their windows after re-decorating while effects are enabled, and the mask texture doesn't update.
Closes #388
=> window-actor: Fix the mask texture not updating after windows re-map after re-decoration

src/core/window.c, src/core/workspace.c
This is [similar to one of the window mapping improvements](https://github.com/linuxmint/Cinnamon/commit/a59f64c352972ca373ad45799e553b76aea2b50f#diff-adc58d0de528049bf386ed40609b6ac9R1128) introduced to the window list applet for 3.8, but uses `clutter_threads_add_timeout` so we can acquire a lock and make Clutter more aware of the timings. The idea is to defer signal emission a bit so we're not blocking the main thread during mapping events.
I used the script from https://github.com/linuxmint/Cinnamon/pull/7251 as a general indicator, along with a stop watch app on my phone.
Before the patch:
Grouped window list - script: 5-6s, stop watch: 9s (using https://github.com/linuxmint/Cinnamon/pull/8092)
Window list - script: 0.5-1s, stop watch: 7s
After:
Grouped window list - script: 0.5s, …
=> Speed up window mapping

src/compositor/meta-window-actor.c, src/core/display.c, src/core/window-private.h, src/core/window.c, src/meta/window.h
`meta_shaped_texture_set_overlay_path` is called in `update_corners`, so it needs to be called before `meta_window_actor_reset_mask_texture` in `check_needs_reshape` because the mask generation depends on the overlay path for framed windows.
This also replaces `MetaFrameBorders` in `check_needs_reshape` with [meta_window_get_client_area_rect](https://github.com/gnome/mutter/commit/ad43cbd70b465af824a9181ee29b84807f8036be) because its an expensive function when the size changes, and the borders only need to be calculated for framed windows.
Closes https://github.com/linuxmint/mint-19.1-beta/issues/50
=> window-actor: Fix corners not updating on size change

src/core/window.c
This fixes a regression introduced in #382 that is causing the position to not be set correctly when a window is tiled.
Closes #396
=> window: Pass the input rect to meta_compositor_tile_window

src/core/window-private.h, src/core/window.c, src/meta/window.h
This adds a `meta_window_is_interesting` method to replace `cinnamon_window_tracker_is_window_interesting`, and simplifies `meta_window_showing_on_its_workspace`.
=> Improvements for Cinnamon's app system

clutter/clutter/clutter-master-clock-default.c, clutter/clutter/clutter-stage.c
This is an improvement for higher refresh rate monitors, though seeing a noticeable reduction of input latency at 59.97-60Hz. Not seeing any change in Muffin's CPU usage. Tested on Nvidia and Mesa.
Note, the diff from upstream is a bit different because we preserve the ability to make the sync method configurable in #355.
Adapted from
https://gitlab.gnome.org/vanvugt/mutter/commit/f17de523482fe10f8a6194f32782086e39976688
https://gitlab.gnome.org/GNOME/mutter/merge_requests/346
=> Clutter master clock improvements

clutter/clutter/clutter-stage.c
> The "after-paint" signal should only be emitted on real stage repaints and not fake stage repaints used in picking. The latter might occur at a much higher and inconsistent rate and is not what apps/toolkits listening for _NET_WM_FRAME_DRAWN care about.
Cherry-picked from https://github.com/GNOME/mutter/commit/93c29318b2994cb23cc88e0c63d923bb0bc92dc8
=> clutter-stage: Don't emit "after-paint" when picking

src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-shaped-texture.c, src/compositor/meta-window-actor.c, src/compositor/meta-window-group.c, src/core/display.c, src/meta/meta-shaped-texture.h
#390 partially fixed this, but some clients need more time after being re-mapped before the mask texture stops being set - such as Virtualbox's seamless window.
Closes #404 
Closes #398 
Closes https://github.com/linuxmint/Cinnamon/issues/8265
=> window-actor: Fix partially visible frameless windows, some window flickering cases

src/compositor/meta-shaped-texture.c, src/compositor/meta-window-actor.c, src/meta/meta-shaped-texture.h
Seeing Cinnamon start with slightly lower memory usage with this patch applied, and improved responsiveness.
Depends on #405
=> Stop caching the shape region in MetaShapedTexture

src/compositor/meta-window-actor.c
The effect was added to soften shadows in 92b32be. This makes it so it's only applied to windows with shadows.
Depends on #405 to avoid a conflict.
=> Window-actor: Only apply desaturation effect if the window has a shadow 

src/compositor/compositor.c, src/compositor/meta-shadow-factory.c, src/meta/meta-shadow-factory.h
Muffin shouldn't rely on signals to callback into components that are within its own scope. Signals do not perform as well and they cause a lock to be placed on signal handler lookups
=> shadow-factory: Replace the changed signal with a function call

src/core/window-private.h, src/core/window.c, src/meta/window.h
This prevents a new icon pixmap from being created on every meta_window_create_icon call.
Returning a pixbuf allows us to skip the GI prop system entirely and gives Cinnamon the icon as quickly as possible.
Requires https://github.com/linuxmint/Cinnamon/pull/8370
=> window: Cache icons if the size is <= icon_size, return a GdkPixbuf

clutter/clutter/clutter-master-clock-default.c, clutter/clutter/clutter-muffin.h, clutter/clutter/x11/clutter-stage-x11.c, src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-window-actor.c, src/core/display-private.h, src/core/display.c, src/core/main.c
This adds support for changing the vsync option without needing to restart Cinnamon, and by extension, enables us to more fully disable compositing overhead for games.
When both vsync and the option to disable compositing of fullscreen windows are both enabled, sync will be toggled on/off for fullscreen or monitor sized windows as they become redirected/unredirected.
Addresses #409
=> Support toggling vsync at runtime for better unredirection control

src/core/window.c
This fixes the window positions not being tracked in the workspace switcher applet for some CSD windows.
=> window: Fix the position-changed signal not firing for CSD windows

src/compositor/cogl-utils.c, src/compositor/cogl-utils.h, src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-sync-ring.c, src/compositor/meta-texture-tower.c
Split from #410.
This reduces calls to `clutter_get_default_backend`, which calls `_clutter_context_get_default`, and causes a synchronous lock to be placed on ClutterContext - this isn't necessary for Muffin's configuration.
Initially tried to repurpose the static pointer in cogl-utils.c, but this resulted in a massive memory leak. This adds a getter to MetaCompositor and uses its reference instead.
Also makes hardware_supports_npot_sizes public so it can only be called once when GL extensions are checked.
=> Avoid getting context from Clutter in frequently called functions

src/compositor/compositor.c, src/compositor/meta-window-actor.c, src/compositor/meta-window-group.c, src/core/constraints.c, src/core/edge-resistance.c, src/core/keybindings.c, src/core/place.c, src/core/screen-private.h, src/core/screen.c, src/core/stack.c, src/core/window-private.h, src/core/window.c
Split from #410.
This caches the outer and client rects, and updates them when the window size changes. The placement of the update calls were chosen based on a [previous upstream optimization](https://github.com/linuxmint/muffin/commit/8779c27f78150970b98e5681acfb5b792d8fea35) for caching frame borders.
=> window: Cache the outer, client rects

src/compositor/compositor-private.h, src/compositor/compositor.c, src/core/core.c, src/core/core.h, src/core/display.c, src/core/frame.c, src/core/frame.h, src/core/prefs.c, src/core/screen.c, src/meta/common.h, src/meta/display.h, src/ui/frames.c, src/ui/frames.h, src/ui/menu.c, src/ui/theme.c, src/ui/ui.c, src/ui/ui.h
This PR is intended to help improve the performance of framed windows, and reduce how far out of sync window positioning is with the  cursor when dragging. 
It is a mix of select upstream commits and some new changes.
- Eliminates usage of `gdk_window_get_device_position` which causes round trips to the X server, and prevents CSD window events from being handled in MetaFrames.
- Frame geometry calculation optimization. `meta_frames_calc_geometry` was getting called often, and limiting it to when the window rect changes improves performance in my testing.
- [Adds a pointer to MetaWindow on MetaUIFrame](https://github.com/gnome/mutter/commit/12135afa5e2016e6234d24dcfecdaa293576719a), so we can replace meta_core_get* round trips with more direct calls.
Depends on #410 because of …
=> Improve sync between the cursor and frames

src/ui/ui.c
This fixes window grab events being propagated to the wrong windows.
Ref https://github.com/linuxmint/cinnamon/issues/8454
=> ui: Don't apply CSD window filtering for button events

src/core/screen.c
Addresses the same issue as #438, but more selectively calls `meta_window_update_monitor`.
=> screen: Ensure monitors update on monitor change

src/core/window.c
This fixes windows initially having an incorrect monitor assigned.
=> window: Update monitor state before showing the window

src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-window-actor-private.h, src/compositor/meta-window-actor.c, src/core/display.c, src/core/screen.c, src/core/window-private.h, src/core/window-props.c, src/core/window.c, src/meta/compositor.h, src/meta/window.h
Reverts:
990e8fab6e752ec17f97ae30aa1a7d47a87a8343
6eeb70bd8d680535eeed547070e9abfcef6f528d
This fixes Skyrim (and probably other Wine games).
I'm still not exactly sure what caused this, but once I have a better idea I will clean these up for another PR.
Ref https://github.com/linuxmint/cinnamon/issues/8454
=> Revert two commits from #410

clutter/clutter/evdev/clutter-input-device-evdev.c
Cherry-picked from https://github.com/gnome/mutter/commit/34ee46022e467fda89a781dd07f90061a42d984d
https://gitlab.gnome.org/GNOME/mutter/issues/529
=> clutter: Fix check for keyboard a11y features

src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-window-actor-private.h, src/compositor/meta-window-actor.c, src/compositor/meta-window-group.c, src/core/window.c, src/core/xprops.c, src/core/xprops.h, src/meta/meta-window-actor.h
This restores actor opacity management without relying on a signal.
- Merges `maybe_desaturate_window` into `meta_window_actor_set_opacity`.
- Only propagates to clutter if the opacity changes.
- Scrolling on title bars opacifies windows unlike the version of this patch from #437.
Ref https://github.com/linuxmint/cinnamon/issues/8454
=> window-actor: override Clutter opacity property and method

clutter/clutter/clutter-actor.c
Cherry-picked from https://github.com/gnome/mutter/commit/ee507d9ab2b2f277447976c3f5ddc55375fef1eb
https://gitlab.gnome.org/GNOME/mutter/merge_requests/511
=> clutter-actor: Keep is_dirty unchanged for culled actors

src/compositor/meta-shadow-factory.c
Cherry-picked from https://github.com/gnome/mutter/commit/3c6a518d40d0ed8d04343f0780100e88f8519ed1
=> compositor: Avoid changing pipeline/source if shadow is not being painted

clutter/clutter/clutter-stage.c, clutter/clutter/cogl/clutter-stage-cogl.c
Cherry-picked from https://gitlab.gnome.org/GNOME/mutter/merge_requests/402
=> clutter-stage: Remove unused variable, double assignment

src/compositor/meta-window-actor.c
This disables Clutter event propagation for MetaWindowActor, which is not needed by our sub-class.
Results in a noticeable perf improvement for me.
=> window-actor: Make actor non-reactive

src/compositor/meta-shadow-factory-private.h, src/compositor/meta-shadow-factory.c, src/compositor/meta-window-actor-private.h, src/compositor/meta-window-actor.c, src/core/window.c, src/meta/meta-shadow-factory.h, src/meta/meta-window-actor.h
This fixes an issue with #449 where client requests didn't propagate due to the max possible value for `guint8` being 255.
=> window-actor: Use int for opacity

clutter/clutter/clutter-main.c, clutter/clutter/clutter-master-clock-default.c, clutter/clutter/clutter-muffin.h, clutter/clutter/cogl/clutter-stage-cogl.c, clutter/clutter/x11/clutter-stage-x11.c, src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-window-actor.c, src/core/display-private.h, src/core/display.c, src/core/main.c, src/core/prefs.c, src/meta/common.h, src/meta/prefs.h, src/org.cinnamon.muffin.gschema.xml.in
Our version of Clutter master clock has a few ways to handle frame timing with sync. This PR exposes them to settings so we can expand the best scenario for people on a wider variety of hardware.
Thanks to Daniel van Vugt for providing the original master clock code.
This includes conflicting bug fix PR #451.
=>  Expose the sync method to preferences

clutter/clutter/clutter-actor.c, clutter/clutter/clutter-muffin.h, src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-window-actor-private.h, src/compositor/meta-window-actor.c, src/compositor/meta-window-group.c, src/core/boxes.c, src/core/screen.c, src/core/window-private.h, src/core/window.c, src/meta/common.h, src/ui/frames.c
- Fixes the workspace switching animation.
- Fixes windows not appearing after workspacing switching.
- Fixes artifacts on CSD Firefox windows.
- Stores the client area rect as a pointer in order to reduce memory allocation.
- Removes some redundant setters in MetaWindowActor, that were used in MetaWindowGroup's paint function.
- Guards against duplicate clip region propagation, so less CPU time is spent on windows with shadows.
=> compositor: Fix workspace switching, improve window dragging smoothness

src/core/display-private.h, src/core/display.c, src/core/errors.c, src/core/screen.c, src/ui/ui.c, src/ui/ui.h
- Replaces `gdk_error_trap_push` with `gdk_x11_display_error_trap_push`
- Replaces `gdk_error_trap_pop` with `gdk_x11_display_error_trap_pop`
- Fetches `GdkDevice` via `gdk_seat_get_pointer`, and caches it on the MetaDisplay struct, so we're not calling the same getters repeatedly in the MetaFrames event dispatcher.
`gdk_display_get_default` will be deprecated in a future version of GTK, but isn't in 3.22. [Attempting to replace it](https://github.com/gnome/mutter/commit/d4c4d6e64d899e67cfd821e1ff869cfc181097be) caused too many issues, so better to wait on that one.
=> Replace some deprecated GDK methods

src/compositor/compositor-private.h
stops 450 lines of build error warnings
=> compositor-private: remove a couple of duplicated lines

src/compositor/meta-window-actor.c, src/core/window.c
When un-fullscreening xed, the windows underneath are still treated as obscured.
C/O @JosephMcc
=> Make sure windows paint before un-fullscreening

src/compositor/compositor.c, src/compositor/meta-background-actor.c, src/compositor/meta-window-actor.c, src/core/constraints.c, src/core/core.c, src/core/display-private.h, src/core/display.c, src/core/edge-resistance.c, src/core/keybindings.c, src/core/main.c, src/core/place.c, src/core/prefs.c, src/core/screen.c, src/core/window-props.c, src/core/window.c, src/core/workspace.c, src/meta/prefs.h, src/ui/frames.c
b77b6ff4732e8830bfb3eda5f11edef82d793f0a
This stores pointers to the static values in prefs.c in a new struct, which is stored on the MetaDisplay struct, and accessible from most muffin code. The benefit of this is it allows us to get GSettings values without calling functions.
Includes #450, #452, and one commit from #464 to avoid conflicts.
=> Add MetaPrefsState struct for retrieving the prefs state without function invocation

src/compositor/meta-window-actor-private.h, src/compositor/meta-window-actor.c, src/core/main.c
7cfa12d258a03a8b0705a795042d52e3bfb5afc8
Currently MetaWindowActor only has a screen reference, which is mostly used to fetch MetaDisplay.
Based on #466 and #475
=> window-actor: Add reference to MetaDisplay

src/compositor/compositor.c
=> compositor: Check if priv is NULL before calling meta_window_actor_should_unredirect

src/core/window.c
The outer rect needs to be updated on drag for edge resistance to work. This conditionalizes it based on if the setting is used. This could probably be guarded even more, but for another merge cycle.
C/O @mtwebster
=> window: Fix edge resistance

src/core/window.c
This is apparently needed so the workspace switcher applet animates window movements in real-time. I don't think this warrants the performance hit for what amounts to eye candy, but I am weary of the debate and would rather more small changes like this be in place than fully reverting hundreds of hours of my work like has been discussed yesterday on Slack.
=> Unconditionalize meta_window_update_outer_rect

src/compositor/meta-window-actor.c
This fixes transparent terminals not being transparent when focused. The `clip_shadow` value is correct, but  it's updating after the paint cycle triggered from `clutter_actor_set_opacity`.
=> window-actor: Update clip_shadow before the redraw

src/core/window.c
This fixes resizing indication in the workspace switcher applet.
=> window: Call update_outer_rect in update_resize

src/compositor/compositor.c, src/core/screen-private.h, src/core/screen.c
This reverts 12a1246d876660a61d95340100df7c82f6b19bba. At the time the code looked like it never would have worked and was removed, but after testing 4.0.6 that appears to only be the case after #424. This restores the original behavior without crashing by deferring the workspace switching until after MetaCompositor is initialized with a managed screen.
Ref https://github.com/linuxmint/cinnamon/issues/8602
=> Fix the current workspace not being selected during startup

src/core/window-private.h
This fixes a build error in display.c, but adding it in window-private.h because it will be compatible with the re-introduction of the compositor patches for 4.4.
=> window-private: Include compositor-private.h

src/compositor/cogl-utils.c
the deprecated routine just calls the new one, so can safely substitute it
=> cogl-utils: remove a deprecation

src/compositor/meta-window-actor.c
This causes redraw freezes on some drivers/configurations after redirection.
=> meta-window-actor: don't toggle sync during runtime

src/ui/theme-parser.c, src/ui/theme-private.h, src/ui/theme.c
Fix themes that are broken by e252272477.
This doesn't restore the icons, but at least fixes the title layout
caused by missing icon size info.
ref: https://github.com/linuxmint/mint19.2-beta/issues/73
=> metacity themes: Fix layout of themes that use mini-icons.

src/compositor/meta-shadow-factory.c
The regression was introduced in https://github.com/linuxmint/muffin/commit/66efde884efce35afd433efbda966774a65c9d85
The rectangle array wasn't being filled up properly.
Screenshot of the issue:
=> meta-shadow-factory: Fix terminal shadows

src/core/window.c
In https://github.com/linuxmint/muffin/commit/89805c059609f2cd48f60148896c057428362cb6
it looks like two lines were removed by mistake, making it impossible to
move windows.
=> window.c: Fix regression on window move

src/compositor/meta-window-actor.c
If the shadow has been removed but the effect is not, the effect is still
wanting to paint the area of the client window and the offset shadow region.
With certain window effects that involve opacity changes, you can end up with
an empty region around the edges of the window that will impact visible window
size.
Fixes #530
=> meta-window-actor.c: Make sure to remove any existing desaturate effect when a window no longer has a shadow.

src/ui/theme.c
This alters no behavior, but stops creating a pixbuf twice for the sole purpose of getting its size.
Adapted from the marco fix of the same original hidpi issue:
https://github.com/mate-desktop/marco/commit/af17e33e008e948e25e3df5dbe0931d0c1cf8908
=> src/ui/theme.c: Use a simpler method for getting an image file's dimensions for hidpi scaling

src/compositor/meta-window-actor.c
It's possible this was accidentally done due to upstream reversing the
logic in this function (set_redirected -> set_unredirected), and the
if/else was also reversed.
https://github.com/GNOME/mutter/commit/56f8d32ca9f87c2be0ed93d42e799d04b17ad08
Original mutter patch that added _detach: 
https://github.com/GNOME/mutter/commit/2ecc50af535d6dbdba07b18b7834979cbb12b41a
bug report:
https://bugzilla.gnome.org/show_bug.cgi?id=693042
Note: For reference, mutter's current implementation has this reversed once more, though no explanation was given, it occurred during some refactoring.  But, our codebase is different enough I'm not going to assume it's correct.
Fixes: linuxmint/cinnamon-screensaver#314
=> meta-window-actor.c: Detach after redirecting, not before unredirecting.

configure.ac
It's not used at all. Taken from [mutter](https://gitlab.gnome.org/GNOME/mutter/-/commit/07dd4d3f93907755992eea718572c8de7a06b3dc).
=> configure.in: Remove gnome-doc-utils unneded dependency

src/core/window-private.h, src/core/window.c, src/meta/window.h
This works more reliable for windows from flatpaks than the usual net_wm_pid.
=> Add function to fetch a window's pid from XCB

clutter/clutter/Makefile.am
Currently, build is failing with:
```
make[4]: *** No rule to make target 'Clutter-0.typelib', needed by 'all-am'.  Stop.
```
due to clutter's `Makefile.am` always trying to generate GObject
Introspection GIR and typelib files, despite the
`--disable-introspection` flag and configure script reporting
introspection being disabled like so:
```
• Extra:
Build introspection data: no
Build X11-specific tests: yes
Build tests using GDK-Pixbuf: yes
Install test suites:
Build examples: no
```
This commit fixes the problem by introducing the check for
`HAVE_INTROSPECTION` flag and skipping GObject files generation.
=> Fix build failure if introspection is disabled

src/compositor/meta-window-actor.c, src/core/window-props.c, src/core/window.c, src/core/xprops.c
When trying to build muffin with `--disable-xsync` option, it fails for
a variety of reasons:
```
compositor/meta-window-actor.c:1292:44: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_serial'
1292 |   frame->sync_request_serial = priv->window->sync_request_serial;
```
```
core/window.c: In function 'meta_window_unmanage':
core/window.c:1865:13: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_timeout_id'
1865 |   if (window->sync_request_timeout_id)
|             ^~
core/window.c:1867:30: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_timeout_id'
1867 |       g_source_remove (window->sync_request_timeout_id);
|                              ^~
core/window.c:1868:13: error: 'MetaWindow' {aka …
```
=> Fix the build without XSync extension enabled

src/compositor/meta-window-actor.c
Followup for commit babce7fed0da86ce5c77fc04b3f794e5cfbbbb70 which added the HAVE_XSYNC checks. Since this is immediately overwritten by the xsync code, it does nothing unless xsync is disabled. Make this explicit by moving it down into an #else section, so that it doesn't generate any code.
/cc @filakhtov
=> fixup defines for HAVE_XSYNC by running fallback code only in else block

src/compositor/meta-background-actor.c
I don't know if this is exactly the correct way to do it, but this
ensures that the transition actors have the correct size after the
stage changes size.
Previously, we queued a relayout on the parent of the transition
actors. I don't know if this just never properly re-layouted the
children, or if another change (possibly the clutter/cogl merge)
changed the layout behavior since then.
Fixes: https://github.com/linuxmint/muffin/issues/542
=> backgrounds: relayout the transition actors on size change

data/theme/metacity-theme-3.xml
With reference to https://github.com/linuxmint/nemo/issues/2402
=> Fallback WM theme - ensure dialogs such as nemo preferences have titlebar buttons

src/compositor/meta-shaped-texture.c
from upstream https://gitlab.gnome.org/vanvugt/mutter/-/commit/d1411c5f84b90f4191baa9706ff30892e6e07f52
said to give 5% render improvement at 4K and lower power use
=> Shaped-texture: Use the REPLACE combine function on opaque areas

Makefile.am, clutter/clutter/Makefile.am, src/Makefile.am, src/compositor/plugins/Makefile.am
When building muffin with slibtool (https://dev.midipix.org/cross/slibtool) it fails, this PR has two commits to fix the build.
1. Several libtool `.la` files are missing as dependencies in some of the `Makefile.am` files.
2. The build fails with `-no-undefined`, this works with GNU libtool because it silently ignores `-no-undefined` while slibtool does not. This requires building `src/compositor/plugins` separately from the rest of `src/` to ensure `libmuffin.la` exists when it is needed.
Full logs:
[muffin-slibtool.1.log](https://github.com/linuxmint/muffin/files/5871673/muffin-slibtool.1.log)
[muffin-slibtool.2.log](https://github.com/linuxmint/muffin/files/5871687/muffin-slibtool.2.log)
=> Fix the build with slibtool.

src/core/window.c
Fixes #585.
This commit makes sure we are actually unmaximising a maximised window, or untiling a tiled one, when the unmaximize function is called. This function gets called more often in Wine to prevent issues in KWin (https://source.winehq.org/git/wine.git/commit/c5ec1585f6e5211a2b63e3435748210552250534).
Mate had a similar issue with a different cause, which was also fixed in the window manager (https://github.com/mate-desktop/marco/commit/60f49ae5a272b737a944065e4199c8b2c8eec8b1).
=> Fix windows that cannot be moved in some Windows applications with Wine >=5.16

src/core/constraints.c, src/core/window-private.h, src/core/window-props.c, src/core/window.c
Windows that were starting out as fullscreen (_NET_WM_FULLSCREEN)
were being initially decorated, as the fullscreen property wasn't
being applied until after window construction and placement. The
decorations also were not being removed at that point, leaving
space around the window which was visible in adjacent monitors.
This patch is a combination of:
https://github.com/GNOME/metacity/commit/829ce2e3ca794d6c17a1ea9f0748ac75be5007fa
https://github.com/GNOME/metacity/commit/7a7aaa338b89c0c66122958e7c6cb56322e73371
and
https://github.com/GNOME/mutter/commit/07f533f617e3771861a92f25d3cc288d3c9d465a
Test cases in the bug report for the original commit that 07f533 reverts
are still behaving properly. See:
https://bugzilla.gnome.org/show_bug.cgi?id=461927
Fixes linuxmint/mint20.2-beta#49
Fixes …
=> Don't allow fullscreen windows to also become decorated.

src/compositor/compositor.c
Offscreen windows may sometimes appear on top of the window
stack even if another fullscreen window is obviously top level.
Fixes https://github.com/linuxmint/muffin/issues/544
See comments in the issue for examples of offending offscreen windows.
=> compositor.c: Skip offscreen windows when unredirecting.

src/core/window.c
We support the atom but it was never being updated. This resulted in csd
windows not having their style properly updated when tiled or maximized.
=> window.c: Properly update gtk_edge_constraints

src/compositor/meta-shadow-factory.c
With csd windows becoming more prevalent, and most themes being rooted in
Adwaita, tweak our window shadows to match. This also brings us inline
with Mutter. Should make window shadows more consistent overall. Also helps
the focused window stand out as on top a bit more.
=> meta-shadow-factory: Tweak window shadows

configure.ac
This code from https://github.com/mate-desktop/mate-common/blob/aa57109bc472ea9340020d819b26d511fb3e002c/macros/mate-common.m4#L25
on my build farm ACLOCAL_AMFLAGS not recognized, and on make stage i see aclocal-1.16 -I  is missing argument
=> improve check ACLOCAL_AMFLAGS

debian/control, debian/rules
Restore kfreebsd and arm archs support to decrease differences with the official debian packages.
About arm archs can be useful also if there are users that want build new version from upstream.
=> [muffin-5.2-test] Small debian improvements

src/core/constraints.c
This fixes the positioning of transient children of fullscreen windows so that they're not affected by panel sizes.
Example: vlc's fullscreen controls got pushed up with a bottom panel, by an amount of pixels equal to the panel height
=> Fix placement of transient children of fullscreen windows

src/core/keybindings.c
This basically reverts the behavior of `handle_move_to_center` back to the old one (with the exception that the window will stay on the screen it currently is, and will not follow the mouse.)
Fixes #622
=> Fix "Center window in screen" behavior

src/core/keybindings.c
Not doing so leaves us in a weird state. The window gets squared corners and
other tiled styling but doesn't actually tile.
=> keybindings.c: Make sure we can tile before we attempt to

debian/control, debian/copyright, debian/rules, debian/tests/libmuffin-dev
- Fix library name for pkgconfig in autopkgtest
- d/control:
add missed libcinnamon-desktop-dev to libmuffin-dev deps
missed increment of breaks/replaces (as rebase was postponed from 5.2
to 5.4
- d/rules: disable wacom in configure for not linux archs
- fix some fields in d/copyright
=> some fixes to debian packaging

src/x11/meta-x11-display.c
This reverts two X11 atoms back to how they were in 5.2
This needs some testing to see if there are any negative side effects.
=> WIP/RFT Revert renaming of the X11 atoms wm_name and gnome_wm_keybindings

src/compositor/compositor.c
I ran into a crash when restarting cinnamon on NixOS:
- (Optionally, to start a NixOS Cinnamon VM on any Linux distribution) [Install Nix](https://nixos.org/manual/nix/stable/installation/installing-binary.html), run `nix --experimental-features "nix-command flakes" run github:bobby285271/test-cinnamon` and login with username and password `test`
- Right click the bottom panel
- Select "Troubleshoot"
- Select "Restart Cinnamon"
- Do some random clicks and see no respond
This PR resolves the problem for me, will appreciate some review with it :bow:
---
Here are the first few lines of backtrace (though probably not useful, you can get the full output in https://github.com/NixOS/nixpkgs/issues/208122):
```gdb
#0  0x00007f57010062ea in clutter_actor_destroy (self=0xb76b40) at …
```
=> compositor: Fix crash when restarting Cinnamon

clutter/clutter/clutter-mutter.h, clutter/clutter/clutter-stage.c, debian/libmuffin0.symbols, meson.build, src/wayland/meta-wayland-pointer.c, src/wayland/meta-wayland-surface.c
```text
(gdb) bt
#0  meta_wayland_surface_get_relative_coordinates (surface=0x0, abs_x=719, abs_y=405, sx=0x7ffe15cea768, sy=0x7ffe15cea76c) at ../src/wayland/meta-wayland-surface.c:1569
#1  0x00007fba6070ec62 in meta_wayland_pointer_get_relative_coordinates
(pointer=pointer@entry=0x564387be1670, surface=surface@entry=0x0, sx=sx@entry=0x7ffe15cea7a8, sy=sy@entry=0x7ffe15cea7ac) at ../src/wayland/meta-wayland-pointer.c:1061
#2  0x00007fba6070ef13 in meta_wayland_pointer_send_enter (surface=0x0, serial=38, pointer_resource=0x56438b2179e0, pointer=0x564387be1670)
at ../src/wayland/meta-wayland-pointer.c:850
#3  meta_wayland_pointer_broadcast_enter (surface=0x0, serial=38, pointer=0x564387be1670) at ../src/wayland/meta-wayland-pointer.c:875
#4  meta_wayland_pointer_set_focus …
```
=> Fix segfault in Wayland session during Alt-Tab when window focus mode is either 'Sloppy' or 'Mouse' (gdb backtrace attached)

src/backends/x11/meta-crtc-xrandr.c
Use the nearest neighbor filter if the scaling factor is an integer. This provides a crisper, less blurry scale when the scale is an integer.
Note that this change only affects fractional scaling when the "scale-up" mode is used.  Scaling down is unaffected by this change, and non-integer scaling up is also unaffected by this change.
This behavior was already in Cinnamon 5.4, but it was lost at some point in between 5.4 and now.
Note finally that the "nearest" filter is a filter guaranteed to exist by the RENDER protocol [1].
[1] https://cgit.freedesktop.org/xorg/proto/renderproto/tree/renderproto.txt
=> meta-crtc-xrandr.c: use nearest neighbor filter for integer randr scales

src/backends/x11/meta-monitor-manager-xrandr.c
Ignore server errors on XRRSetMonitor().  A similar fix appears in mutter [1].
The RandR protocol [2] states concerning RRSetMonitor that:
> If 'name' matches an existing Monitor on the screen, the
> existing one will be deleted as if RRDeleteMonitor were called.
Unfortunately, this behavior is not the case in practice, and if an existing monitor with the same name exists the server generates a BadValue error [3].  While this was fixed very recently in the Xorg xserver [3], it is unclear when these changes will make it to most distributions due to how long it has been since a formal Xorg xserver major release.  Therefore, we must ignore this error to prevent muffin from aborting if a monitor with the same name already exists, a common condition upon restarting cinnamon or calling …
=> Ignore XRRSetMonitor() errors and delete existing monitors with same name

clutter/clutter/clutter-offscreen-effect.c
In order to enable all effects in the "Cinnamon Burn My Windows" extension it's required that the clutter OffscreenEffect.get_target() API is available to Cjs. I believe that the "(skip)" comment text is a GObject-Introspection annotations that prevents the API from being exposed as a API call in Cjs. The current GNOME equivalent is OffscreenEffect.get_pipeline() which is available to Gjs. https://github.com/GNOME/mutter/blob/625965d956a8818b77eadbdf0ae6e5edbf60b029/clutter/clutter/clutter-offscreen-effect.c#L666
=> Make clutter_offscreen_effect_get_target available to Cjs

clutter/clutter/clutter-actor.c, clutter/clutter/clutter-timeline.c, cogl/cogl/cogl-onscreen.h, cogl/cogl/cogl-pipeline.h, src/tests/clutter-test-utils.c
Whenever you’re describing a function that takes a callback, you should always annotate the callback argument with the argument that contains the user data using the (closure argument) annotation
You should not annotate the data argument with a unary (closure).
The unary (closure) is meant to be used when annotating the callback type
Ref:
https://gitlab.gnome.org/GNOME/mutter/-/commit/077eb80a8d9bb2968c2bfac959c2f2ca966ca7e7
=> gir: Correct usage of the closure annotation

src/core/constraints.c
If the titlebar of a window has been moved above the screen by a user via an unconstrained move, then any constrained user resize following this move will cause the window to jump below the top of the screen or cause other glitchy behavior.
This commit removes the constraint that the titlebar of a window must be below the top of the screen for any resize that is both (1) triggered by a user and (2) is a resize that affects only the left, right, or bottom edges of the window.  This allows users to move a window partially above the screen and then resize the window to be wider or resize the bottom edge of the window to make it taller or shorter.
This is a backport of 5ba364a9476905d9b92e7dc6cdc2f273bcda2498.
=> constraints.c: Allow resize of windows moved above screen

src/core/display.c, src/meta/display.h
This exposes monitor names to gobject introspection via MetaDisplay. A corresponding Cinnamon PR is underway.
=> Exposes monitor names

clutter/clutter/clutter-offscreen-effect.c, clutter/clutter/clutter-offscreen-effect.h
In order to enable the full set of effect in the CinnamonBurnMyWindows extension, I need access to OffscreenEffect's CoglPipeline in Cjs. I had hopped that making get_target() available to Cjs (PR #702) would give me access to the pipeline, but it turns out that get_target() is returning the target as a CoglMaterial which I probably should have known would only give me access to the CoglMaterial APIs in Cjs. This proposed change copies the get_target() code and renames the copy to get_pipeline() and returns the target as a CoglPipeline rather than casting it to a CoglMaterial.
I am not setup to build muffin for testing these changes, but the changes are minor modifications to copies of the existing get_target() code. If these changes are accepted, I am not sure what Cinnamon version it …
=> Add get_pipeline() API

clutter/clutter/meson.build, src/compositor/plugins/meson.build, src/meson.build
Given sufficiently high or simply random parallelism, it was possible to build various source files that included this generated header, without having coincidentally built the header previously. It then failed to compile, since there was no actual guarantee the header would come first. Add explicit header-only dependencies by adding the header as additional sources to targets that draw it in.
Fixes:
```
* QA Notice: missing ninja dependencies in /var/tmp/portage/x11-wm/muffin-6.4.1/work/muffin-6.4.1-build:
[...]
* Processed 517 nodes.
* Error: There are 249 missing dependency paths.
* 249 targets had depfile dependencies on 1 distinct generated inputs (from 1 rules)  without a non-depfile dep path to the generator.
* There might be build flakiness if any of the targets listed above are …
```
=> meson: fix some implicit ordering dependencies on generated headers

src/wayland/meta-wayland-outputs.c, src/wayland/meta-wayland-versions.h
wl_output v3 allows clients to tell the
server that it can clean up the related wl_resource.
wl_output v4 adds the name and description events already present in xdg_output. Some clients may rely on that information instead of xdg-output-v1
=> [Wayland] Bump wl_output interface to v4

src/wayland/meta-wayland-dma-buf.c
This is from https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1999 and landed as https://gitlab.gnome.org/GNOME/mutter/-/commit/922878ac upstream, but muffin isn't even up-to-date with [41.1](https://gitlab.gnome.org/GNOME/mutter/-/commits/41.1) (or [40.9](https://gitlab.gnome.org/GNOME/mutter/-/commit/18754031)) and thus missed it still nearly 4 years later.
This is now required to run the latest https://waydro.id Android 13 images, and I've confirmed locally this is simply all that was missing:
@mtwebster if you'd consider this along with a bugfix release that'd be great, Cinnamon Wayland users are currently unable to use Waydroid with the latest images without additional workarounds (such as `gralloc.gbm.legacy=true`) :)
This also closes …
=> wayland/dma-buf: Add support for BGR_8888 formats

config.h.meson, data/org.cinnamon.muffin.wayland.gschema.xml.in, meson.build, src/backends/meta-settings-private.h, src/backends/meta-settings.c, src/wayland/meta-xwayland.c
Recent versions of Xwayland can allow or disallow X11 clients from different endianess to connect.
Add a setting to configure this feature from Muffin, who spawns Xwayland.
Disabled by default, since this feature have potential security issues.
Closes https://github.com/linuxmint/wayland/issues/124
=> [Xwayland] Add Xwayland byte-swapped clients support
