linuxmint/muffin

src/core/screen-private.h, src/core/screen.c, src/core/stack-tracker.c, src/core/stack.c, src/core/util.c, src/core/window.c, src/meta/screen.h, src/meta/util.h, src/meta/window.h
Based on https://github.com/GNOME/gnome-shell/commit/6119b447469c71c36b15c0d0fa8c1cfa24289778
Requires: https://github.com/linuxmint/Cinnamon/pull/5229
=> Improve tracking of fullscreen windows

src/compositor/meta-window-actor.c
https://github.com/GNOME/mutter/commit/079dd60e3d5cd6a6e1070f89f4f7277423bda727#diff-5d2e6395ac2f32aae711a05663b64d18
=> use g_clear_pointer to clean up finalization code

src/compositor/compositor.c, src/compositor/meta-background-actor.c, src/compositor/meta-window-actor.c, src/compositor/meta-window-group.c, src/meta/meta-window-actor.h
Left the default plugin untouched for now. It needs more general work and isn't very stable currently
=> compositor: Clean up a bunch of deprecated clutter functionality

src/ui/frames.c, src/ui/frames.h, src/ui/ui.c, src/ui/ui.h
https://github.com/GNOME/mutter/commit/fc87a635b20cd5928e155f895907436c68633222
=> frames: Remove expose_delayed

src/core/main.c
Fixes https://github.com/linuxmint/muffin/issues/225
=> change to sys/wait.h

src/core/window-private.h, src/core/window-props.c, src/core/window.c, src/meta/atomnames.h, src/meta/window.h
(see linuxmint/Cinnamon@d1f5fe9cd9621485ae6ff)
=> [3.6] window.c: Add meta_window_get_icon_name

src/core/window.c
Speed up window creation.
See https://github.com/linuxmint/Cinnamon/pull/7251
=> Faster window mapping

src/core/window.c
This fixes some cases where we weren't notifying when the
property has actually changed.
notify_tile_type() is combined into set_tile_type() and only
emitted when tile-type changes. The direct property change in
unmaximize_internal() is converted to use set_tile_type() and
a second redundant set in the same block is removed.
=> window.c: always notify when tile-type property changes

src/compositor/meta-texture-tower.c
Based on
https://github.com/GNOME/mutter/commit/e320b06aaade305552a3f58d90f8a1c5b983e827
https://github.com/GNOME/mutter/commit/249468bbea47a24e31945452c13414f82d40c105
https://github.com/GNOME/mutter/commit/d0b870d3a9f4e5e90c42bfa2663b205a14c4b180
https://github.com/GNOME/mutter/commit/f42682711b187489bfb8386ed0979db1edeed481
=> Modernize texture tower

src/compositor/meta-sync-ring.c
Based on
https://github.com/gnome/mutter/commit/299ed424d36921dc2fa6b5d33f9ef32d0532e5d6
=> compositor: Handle fences in the frontend X connection

src/compositor/compositor.c
Based on:
https://github.com/GNOME/mutter/commit/4f2bb583bf8c7f7e37f74ba09006a17c6974d792
https://github.com/GNOME/mutter/commit/436d3ff8a9f8c415728eca6a7afba30cc5b2ec32
=> compositor: Don't connect to the stage's paint signal 

src/compositor/compositor-private.h
https://gitlab.gnome.org/GNOME/mutter/merge_requests/152
=> compositor: Default to META_SYNC_DELAY == 0

src/core/window.c
Based on:
https://github.com/GNOME/mutter/commit/f9c625924e5358afd3e47733e68d166770edd496
https://github.com/GNOME/mutter/commit/e3622275147181a2876e45397f5fc7ed063b8bb8
https://github.com/GNOME/mutter/commit/1fe5b3e7d5c40870d45a481fc96f70bda372c2de
https://github.com/GNOME/mutter/commit/9402691aaadfb38d7b2aa29b9fdda81266b6e9ba
https://github.com/GNOME/mutter/commit/d8c2933c5863876cd15983d068c97fc9e0ba5079
https://github.com/GNOME/mutter/commit/aa848134007502175927c69d667789c70f891fb4
=> window: Various performance improvements

src/compositor/meta-shaped-texture.c
Based on:
https://github.com/GNOME/mutter/commit/c9c32835409046556148d850796210c605ad9998
=> shaped-texture: Disable mipmapping during animation

src/core/display.c
Based on:
https://github.com/gnome/mutter/commit/b112d982781f9f3618784ddce03c0163ebac54db
=> Improve handling of tracking the old focused window during restart

src/compositor/meta-window-actor.c, src/core/window.c
Ref https://github.com/linuxmint/Cinnamon/issues/8020
=> window-actor: Fix window shading

src/compositor/meta-window-actor.c
Closes https://github.com/linuxmint/Cinnamon/issues/8020
Ref https://github.com/linuxmint/muffin/issues/380
=> window-actor: Fix window artifacts on size/position change

src/compositor/meta-shaped-texture.c
Closes #388 
Ref https://github.com/linuxmint/Cinnamon/issues/8085
=> shaped-texture: Return early if shape_region is NULL in ensure_mask

src/compositor/cogl-utils.c
Closes https://github.com/linuxmint/Cinnamon/issues/8185
Note: CI was passing before I rebased on to master (4.0.6), it's failing because of a network error pulling the tarball.
=> cogl-util: Use original meta_texture_rectangle_new for older GPUs

src/compositor/meta-window-actor.c, src/core/display-private.h, src/core/display.c
=> Avoid usage of g_getenv in frequently called functions

src/compositor/compositor-private.h, src/compositor/compositor.c, src/compositor/meta-window-actor.c, src/compositor/meta-window-group.c, src/core/screen-private.h, src/core/screen.c, src/meta/screen.h
Adapted from
https://github.com/gnome/mutter/commit/cd905a34fb18666376b44bbd670c8b8e855df149
=> Phase out MetaCompScreen

src/compositor/compositor.c
=> compositor: Fix tiling overlay placement

src/compositor/meta-window-actor.c
- Updates the naming scheme of the static functions to reflect what they're really doing. If they even get called, we've already checked if we need a pixmap, shape region, etc.
- Instead of returning early inside these functions, prevent them from being called.
=> window-actor: Clean up the pre-paint functions

src/compositor/compositor-private.h, src/compositor/compositor.c, src/core/display.c, src/meta/display.h
This will be used to replace the JS version of this code in https://github.com/linuxmint/cinnamon/pull/8465.
=> Add meta_display_popup_window_visible

src/core/window.c
Ref https://github.com/linuxmint/cinnamon/issues/8454
=> window: Fix the snap OSD getting stuck

src/compositor/compositor.c
=> Fix unredirected windows not being clipped out of the stage

src/core/boxes.c
=> boxes: Return if the rect pointers are null

src/compositor/meta-window-actor.c
For https://github.com/linuxmint/cinnamon/pull/8596
=> window-actor: Use source actor for the close, minimize effects

src/ui/ui.c
Ref https://github.com/linuxmint/cinnamon/issues/8602
=> Fix segfault when using cinnamon --replace

src/compositor/meta-window-actor.c
=> window-actor: Fix segfault in meta_window_actor_should_unredirect

src/core/main.c
This fixes a segfault when trying to start muffin's standalone executable
=> Fix standalone muffin executable

data/org.cinnamon.muffin.gschema.xml.in, src/core/prefs.c
In tandem with linuxmint/cinnamon#11143
=> Support multiple key bindings for 'locate-pointer-key'

src/core/keybindings.c, src/meta/display.h
=> tiling: Expose actions used by keybindings.

meson.build
See also: mesonbuild/meson#9300
Similar to: linuxmint/nemo-extensions#495
=> Fix a meson warning

data/meson.build, meson.build, src/meson.build, src/tests/meson.build
Similar to linuxmint/cinnamon#11870
Similar to linuxmint/cinnamon-control-center#318
Similar to linuxmint/cinnamon-desktop#234
Similar to linuxmint/cinnamon-menus#67
Similar to linuxmint/cinnamon-screensaver#444
Similar to linuxmint/cinnamon-session#155
Similar to linuxmint/cinnamon-settings-daemon#383
Similar to linuxmint/cjs#119
Similar to linuxmint/nemo#3316
Similar to linuxmint/nemo-extensions#496
Similar to linuxmint/xapp#172
=> Fix meson.build deprecations up to 0.56.0

meson.build
Based on https://github.com/GNOME/mutter/commit/533e6768dace01c7ef7d4eaf122e30b860f46ba5
=> build: Use Xwayland pkg-config if available

src/core/window.c
This should fix an issue (#656) where in some scenarios after tiling across monitors, windows would full screen onto the wrong monitor. The change updates the meta_window_tile so that saved_rect and unconstrained_rect are adjusted based on the target monitor’s work area which ensures consistent behaviour on the intended monitor. While this approach resolves the issue, I haven't worked with Muffin's codebase before, so feedback on improving the implementation is welcome.
=> window.c: Update saved_rect to target monitor work area on tiling
